# Generated by Django 3.2.9 on 2021-11-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211102_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placer', to='app.profile'),
        ),
    ]
