# Generated by Django 3.2.9 on 2021-11-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='lockedUSDtot',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bank',
            name='treasureUSD',
            field=models.FloatField(default=10000),
        ),
    ]
