# Generated by Django 3.2.9 on 2021-11-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211119_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
