# Generated by Django 3.2.9 on 2021-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='openingAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(1, 'Buy_Market'), (2, 'Sell_Market'), (3, 'Buy_Limit_Fast'), (4, 'Sell_Limit_Fast'), (5, 'Buy_Limit_Full'), (6, 'Sell_Limit_Full'), (99, 'Referral')], default=1),
        ),
    ]
